specs = {
    "turbineA1": {"ws_range": "<7.5", 
                  "turbine_rating": "1.695", 
                  "rotor_diameter": "97", 
                  "hub_height": "80",
                  "specific_power": "230"},
    "turbineA2": {"ws_range": "7.5-8", 
                  "turbine_rating": "1.791", 
                  "rotor_diameter": "94", 
                  "hub_height": "80",
                  "specific_power": "260"},
    "turbineA3": {"ws_range": ">8", 
                  "turbine_rating": "1.922", 
                  "rotor_diameter": "92", 
                  "hub_height": "80",
                  "specific_power": "290"},
    "turbineB1": {"ws_range": "<7", 
                  "turbine_rating": "4", 
                  "rotor_diameter": "173", 
                  "hub_height": "112",
                  "specific_power": "170"},
    "turbineB2": {"ws_range": "7-8", 
                  "turbine_rating": "4", 
                  "rotor_diameter": "160", 
                  "hub_height": "105",
                  "specific_power": "199"},
    "turbineB3": {"ws_range": ">8", 
                  "turbine_rating": "4", 
                  "rotor_diameter": "147", 
                  "hub_height": "99",
                  "specific_power": "236"},
    "turbineC1": {"ws_range": "<7", 
                  "turbine_rating": "6", 
                  "rotor_diameter": "196", 
                  "hub_height": "120",
                  "specific_power": "199"},
    "turbineC2": {"ws_range": "7-8", 
                  "turbine_rating": "6", 
                  "rotor_diameter": "184", 
                  "hub_height": "112",
                  "specific_power": "226"},
    "turbineC3": {"ws_range": ">8", 
                  "turbine_rating": "6", 
                  "rotor_diameter": "170", 
                  "hub_height": "105",
                  "specific_power": "264"}
}

