# s3://tsdat-prod/storage/root/awaken/data/sa1.met_z01.b0/sa1.met_z01.b0.20221001.190000.nc
triggers:
  - .*/awaken/.*\.met.*z.*\.nc

inputs:
  converter: utils.converters.from_netcdf_to_csv
  variables:
    # - time
    - wind_speed
    - wind_direction

outputs:
  storage_root: timestream/jobs/{date}.{time}/awaken/{dataset}/
