# {sa1.met.z01.b0}.{20221001}.{190000}.nc
triggers: [.*z06.*\.csv, .*z06.*\.csv]

inputs:
  reader: pipelines.example_pipeline.pipeline.ExamplePipeline
  variables:
    - time
    - wind_speed
    - wind_direction

outputs:
  bucket_name: a2e-athena-test
  storage_root: timestream/jobs/{date}.{time}/awaken/{dataset}/
